### ISSUE TITLE
Apartado 2.4 "Eventos"

### ISSUE THREAD

**Issue by dma1009** [see1004/Ing_Gest_Poyectos_101_2023#10]
Por otra parte tenemos la pila de sprint que es la lista de todas las tareas necesarias para construir las historias de usuario que se van a realizar en un sprint.  Será útil para tener una comunicación visual sobre el avance del sprint y se deben mostrar la lista de tareas, los responsables de cada tarea, el estado en el que se encuentran estas…
El “incremento”: Es la parte de producto que se encuentra en condiciones de ser entregada al cliente; es decir: terminada, probada y operativa. Hay un incremento en cada sprint a excepción del primero. que contiene los elementos básicos de un proyecto
Reunión de planificación del sprint: marca el inicio de cada sprint. Se determina su objetivo y las tareas necesarias para conseguirlo. Debe dar respuesta a tres preguntas: ¿Por qué es valioso este sprint?, ¿Qué se puede hacer en el sprint? y ¿Cómo se va a realizar el trabajo seleccionado?
Durante la reunión de planificación del sprint, el scrum master asignado, además de moderar la reunión, deberá seguir una serie de responsabilidades:
-Llevar a cabo esta reunión antes de cada sprint.
-Asegurar que el propietario del producto presenta la correspondiente pila del producto, así como favorecer el diálogo entre los desarrolladores y este último, permitiendo de este modo alcanzar un acuerdo en términos de lo que deberá incluir el respectivo incremento.
-Asegurar que todas las decisiones tomadas han sido de carácter realista.
-Cuando finaliza la reunión, deberán estar determinados correctamente los objetivos, las tareas, la duración y la “definición de hecho” del sprint.

Scrum diario: Breve reunión diaria en la que el equipo se pone al día. El protocolo más frecuente es que cada miembro informe de lo realizado el día anterior, lo que tiene previsto hacer a continuación y si prevé algún impedimento. Los responsables son los desarrolladores.
Revisión del sprint: Análisis e inspección del “incremento”
Retrospectiva del sprint: Reunión al finalizar el sprint en la que el equipo analiza aspectos de su forma de trabajo y crea un plan de mejoras, para aplicarlo en la siguiente iteración.

**Comment by dma1009** [comment]
Corrección del apartado
Eventos del desarrollo Scrum Master
Reunión de planificación del sprint
Marca el inicio de cada sprint. Se determina su objetivo y las tareas necesarias para conseguirlo. Debe dar respuesta a tres preguntas: ¿Por qué es valioso este sprint?, ¿qué se puede hacer en el sprint?, ¿cómo se va a realizar el trabajo seleccionado? Durante la reunión de planificación del sprint, el scrum master asignado, además de moderar la reunión, deberá seguir una serie de responsabilidades: -Llevar a cabo esta reunión antes de cada sprint. -Asegurar que el propietario del producto presenta la correspondiente pila del producto, así como favorecer el diálogo entre los desarrolladores y este último, permitiendo de este modo alcanzar un acuerdo en términos de lo que deberá incluir el respectivo incremento. -Asegurar que todas las decisiones tomadas han sido de carácter realista. -Cuando finaliza la reunión, deberán estar determinados correctamente los objetivos, las tareas, la duración y la “definición de hecho” del sprint.

Scrum diario
Breve reunión diaria en la que el equipo se pone al día. El protocolo más frecuente es que cada miembro informe de lo realizado el día anterior, lo que tiene previsto hacer a continuación y si prevé algún impedimento. Los responsables son los desarrolladores.

Revisión del sprint
Análisis e inspección del “incremento”

Retrospectiva del sprint
Reunión al finalizar el sprint en la que el equipo analiza aspectos de su forma de trabajo y crea un plan de mejoras, para aplicarlo en la siguiente iteración.

**Comment by jbs1009** [comment]
Corrección del punto de Revisión del Sprint

Revisión del sprint
Análisis e inspección del “incremento”. A esta reunión acuden tanto el equipo scrum como todas las partes interesadas. De este modo, los desarrolladores implicados informan y exponen las historias de usuario llevadas a cabo con éxito, así como aquellas que hayan sido ligeramente modificadas y las que no haya sido posible realizar. Asimismo, las partes interesadas en el producto, aportan nuevas sugerencias y preguntas.
