### ISSUE TITLE
Apartado 2.5 "Medición y estimación ágil"

### ISSUE THREAD

**Issue by dma1009** [see1004/Ing_Gest_Poyectos_101_2023#11]
Es importante realizar una medición del tiempo empleado para desarrollar una estimación del tiempo que nos ocuparán los siguientes scripts. El grado de avance del proyecto se mide según el tiempo que queda pendiente, no el tiempo que ya se ha empleado.

- El «punto» o «punto de historia»:  Es el tamaño relativo de tareas que se suele emplear, dependerá de la organización.

- El «tiempo ideal»: tiempo de trabajo en condiciones ideales y el tiempo que tardara en realizar la tarea.

**Comment by dma1009** [comment]
Corrección del apartado

Medición y estimación ágil
Es importante realizar una medición del tiempo empleado para desarrollar una estimación del tiempo que nos ocuparán los siguientes scripts. El grado de avance del proyecto se mide según el tiempo que queda pendiente, no el tiempo que ya se ha empleado.

El «punto» o «punto de historia» es el tamaño relativo de tareas que se suele emplear, dependerá de la organización.

El «tiempo ideal» es el tiempo de trabajo en condiciones ideales y el tiempo que tardará en realizarse la tarea.

**Comment by jbs1009** [comment]
Corrección: Se añade más información al concepto de "punto de historia", así como el concepto de "tiempo real"

Es importante realizar una medición del tiempo empleado para desarrollar una estimación del tiempo que nos ocuparán los siguientes scripts. El grado de avance del proyecto se mide según el tiempo que queda pendiente, no el tiempo que ya se ha empleado.

El «punto» o «punto de historia», que es el tamaño relativo de tareas que se suele emplear, dependerá de la organización. Así, se puede comparar o estimar el tamaño y/o la dificultad de una tarea respecto a otra ya conocida.

El «tiempo ideal» es el tiempo de trabajo en condiciones ideales y el tiempo que tardará en realizarse la tarea. Es por ello que no deberá ser confundido con el «tiempo real», en el cual, además de carga de trabajo estimada, será necesario tener en cuenta la presencia de inevitables distracciones e impedimentos, que resulten en emplear una cantidad de tiempo mayor a la estimada en condiciones ideales.

**Comment by jbs1009** [comment]
Corrección: Se añade más información al concepto de "punto de historia", así como el concepto de "tiempo real"

Es importante realizar una medición del tiempo empleado para desarrollar una estimación del tiempo que nos ocuparán los siguientes scripts. El grado de avance del proyecto se mide según el tiempo que queda pendiente, no el tiempo que ya se ha empleado.

El «punto» o «punto de historia», que es el tamaño relativo de tareas que se suele emplear, dependerá de la organización. Así, se puede comparar o estimar el tamaño y/o la dificultad de una tarea respecto a otra ya conocida.

El «tiempo ideal» es el tiempo de trabajo en condiciones ideales y el tiempo que tardará en realizarse la tarea. Es por ello que no deberá ser confundido con el «tiempo real», en el cual, además de carga de trabajo estimada, será necesario tener en cuenta la presencia de inevitables distracciones e impedimentos, que resulten en emplear una cantidad de tiempo mayor a la estimada en condiciones ideales.
