### ISSUE TITLE
Corregir los posibles errores ortográficos y de contenido del documento.

### ISSUE THREAD

**Issue by see1004** [see1004/Ing_Gest_Poyectos_101_2023#19]

**Comment by dma1009** [comment]
Contenido redundante en el apartado 2.3. Corrección:
Durante la reunión de planificación del sprint, el cliente colaborará con el equipo de desarrollo para determinar las historias de usuario que conformarán el primero de los sprints.

**Comment by dma1009** [comment]
Correción Apartado 2.5
# Medición y estimación ágil
Es importante realizar una medición del tiempo empleado para desarrollar una estimación del tiempo que nos ocuparán los siguientes scripts. El grado de avance del proyecto se mide según el tiempo que queda pendiente, no el tiempo que ya se ha empleado.

El «punto» o «punto de historia» es el tamaño relativo de tareas que se suele emplear, dependerá de la organización.

El «tiempo ideal» es el tiempo de trabajo en condiciones ideales y el tiempo que tardará en realizarse la tarea.

**Comment by dma1009** [comment]
Corrección Apartado 2.3 Definitivo
La pila del producto
El objetivo de la pila del producto es describir el estado que tendrá el producto en el futuro y que muestra la visión compartida por el equipo. Se conoce como “pila del producto” el conjunto de objetivos, funcionalidades y requisitos marcados por el cliente que deben ser llevados a cabo durante la realización del proyecto, ordenados según su prioridad. Estas indicaciones se denominan “historias de usuario”. Dado que se trata de un artefacto dinámico, esto permitirá adaptar y evolucionar los contenidos de las misma en función de las circunstancias cambiantes a las que se enfrente el desarrollo del producto.

Historias de usuario
Las historias de usuario de la pila del producto que pueden ser incorporados a un sprint son aquellas que están definidas, pre estimadas, son asumibles por sí mismas en un único sprint y se han establecido los criterios para considerarlas terminadas. Se las conoce con el término “preparada”.

Reunión de planificación
Durante la reunión de planificación del sprint, el cliente colaborará con el equipo de desarrollo para determinar las historias de usuario que conformarán el primero de los sprints.

La pila del sprint
Lista de todas las tareas necesarias para construir las historias de usuario que se van a realizar en un sprint. Será útil para tener una comunicación visual sobre el avance del sprint. Se deben mostrar la lista de tareas, los responsables de cada tarea, el estado en el que se encuentran estas…

El incremento
Parte de producto que se encuentra en condiciones de ser entregada al cliente; es decir, terminada, probada y operativa. Hay un incremento en cada sprint a excepción del primero, que contiene los elementos básicos del proyecto.

**Comment by dma1009** [comment]
Correción Final apartado 2.4
Eventos del desarrollo Scrum Master
Reunión de planificación del sprint
Marca el inicio de cada sprint. Se determina su objetivo y las tareas necesarias para conseguirlo. Debe dar respuesta a tres preguntas: ¿Por qué es valioso este sprint?, ¿qué se puede hacer en el sprint?, ¿cómo se va a realizar el trabajo seleccionado? Durante la reunión de planificación del sprint, el scrum master asignado, además de moderar la reunión, deberá seguir una serie de responsabilidades: -Llevar a cabo esta reunión antes de cada sprint. -Asegurar que el propietario del producto presenta la correspondiente pila del producto, así como favorecer el diálogo entre los desarrolladores y este último, permitiendo de este modo alcanzar un acuerdo en términos de lo que deberá incluir el respectivo incremento. -Asegurar que todas las decisiones tomadas han sido de carácter realista. -Cuando finaliza la reunión, deberán estar determinados correctamente los objetivos, las tareas, la duración y la “definición de hecho” del sprint.

Scrum diario
Breve reunión diaria en la que el equipo se pone al día. El protocolo más frecuente es que cada miembro informe de lo realizado el día anterior, lo que tiene previsto hacer a continuación y si prevé algún impedimento. Los responsables son los desarrolladores.

Revisión del sprint
Análisis e inspección del “incremento”

Retrospectiva del sprint
Reunión al finalizar el sprint en la que el equipo analiza aspectos de su forma de trabajo y crea un plan de mejoras, para aplicarlo en la siguiente iteración.

**Comment by dma1009** [comment]
Correción 1.1
La gestión ágil surge como alternativa a la gestión predictiva, que se enfoca en planificar, presupuestar y cumplir plazos fijos. La gestión predictiva se centra en la planificación, en el cálculo de presupuesto y en el marco de plazos de entrega. Se considera éxito terminar el proyecto sin superar el coste acordado, antes de la fecha límite y con todas las funciones del plan inicial. La gestión ágil se adapta a los cambios y se enfoca en entregar resultados tangibles y rápidos y que aporten un valor al cliente.

**Comment by dma1009** [comment]
Correción en #NoEstimates
Algunos equipos de desarrollo bien experimentados en trabajar acorde a las metodologías ágiles, rehúsan de emplear técnicas de estimación, suponiendo así buscar otras formas de sincronizar las entregas. La estimación en la pared utilizando papeles adhesivos, permite apreciar en un golpe de vista las historias de usuario de la pila del producto. El equipo de desarrolladores coloca más a la derecha en la pared las tareas de mayor tamaño, mientras que el propietario del producto coloca más arriba las tareas de prioridad más elevada.

**Comment by dma1009** [comment]
Correcciones:
Primera línea de "sprint": -iteraciones-

**Comment by dma1009** [comment]
Corrección en 3.1: En el último apartado, es "DIRECTO" no "DIRECTA"
Corrección 3.3: La última línea la movemos al siguiente punto

**Comment by jbs1009** [comment]
CORRECCIÓN APARTADO 2.3: Ligeras modificaciones de contenido, así como revisión de errores tipográficos.

La pila del producto
El objetivo de la pila del producto es describir el estado que tendrá el producto en el futuro y que muestra la visión compartida por el equipo. Se conoce como “pila del producto” al conjunto de funcionalidades, correcciones y mejoras, marcadas por el cliente y demás partes interesadas, que deben ser llevadas a cabo durante la realización del proyecto, ordenados según su prioridad y que serán implementadas en los sucesivos sprints. Estas indicaciones se denominan “historias de usuario”. Dado que se trata de un artefacto dinámico, esto permitirá adaptar y evolucionar los contenidos de las misma en función de las circunstancias cambiantes a las que se enfrente el desarrollo del producto.

Historias de usuario
Las historias de usuario de la pila del producto que pueden ser incorporadas a un sprint son aquellas que están definidas, preestimadas, son asumibles por sí mismas en un único sprint y de las cuales se han establecido los criterios para considerarlas terminadas. Se las conoce con el término “preparadas” o "ready". Durante la reunión de planificación del sprint, el cliente colaborará con el equipo de desarrollo para determinar las historias de usuario que serán incorporadas al finalizar el sprint en cuestión.

La pila del sprint
Lista de todas las tareas necesarias para construir las historias de usuario que se van a realizar en un sprint. Será útil para tener una comunicación visual sobre el avance del sprint. Se deben mostrar la lista de tareas, los responsables de cada tarea, el estado en el que se encuentran estas… Esta solamente podrá ser modificada o actualizada por los propios desarrolladores del producto.

El incremento
Parte de producto que se encuentra en condiciones de ser entregada al cliente, es decir, terminada, probada y operativa. Hay un incremento en cada sprint a excepción del primero, denominado generalmente como "sprint cero", que contiene los elementos básicos del proyecto.

**Comment by jbs1009** [comment]
CORRECCIONES EN EL APARTADO 2.4: Se ha añadido algo más de información importante en relación a la Revisión del sprint

Revisión del sprint
Análisis e inspección del “incremento”. A esta reunión acuden tanto el equipo scrum como todas las partes interesadas. De este modo, los desarrolladores implicados informan y exponen las historias de usuario llevadas a cabo con éxito, así como aquellas que hayan sido ligeramente modificadas y las que no haya sido posible realizar. Asimismo, las partes interesadas en el producto, aportan nuevas sugerencias y preguntas.

**Comment by jbs1009** [comment]
CORRECCIONES EN EL APARTADO 2.5: Se ha añadido alguna idea más sobre los "puntos de historia", así como el concepto de "tiempo real".

Es importante realizar una medición del tiempo empleado para desarrollar una estimación del tiempo que nos ocuparán los siguientes scripts. El grado de avance del proyecto se mide según el tiempo que queda pendiente, no el tiempo que ya se ha empleado.

El «punto» o «punto de historia», que es el tamaño relativo de tareas que se suele emplear, dependerá de la organización. Así, se puede comparar o estimar el tamaño y/o la dificultad de una tarea respecto a otra ya conocida.

El «tiempo ideal» es el tiempo de trabajo en condiciones ideales y el tiempo que tardará en realizarse la tarea. Es por ello que no deberá ser confundido con el «tiempo real», en el cual, además de carga de trabajo estimada, será necesario tener en cuenta la presencia de inevitables distracciones e impedimentos, que resulten en emplear una cantidad de tiempo mayor a la estimada en condiciones ideales.

**Comment by dma1009** [comment]
Eliminar reuniones de planificación del apartado artefactos del capítulo II
