### ISSUE TITLE
Apartado 1.1 "Agilidad"

### ISSUE THREAD

**Issue by see1004** [see1004/Ing_Gest_Poyectos_101_2023#6]
La gestión ágil surge como alternativa a la gestión predictiva, que se enfoca en planificar, presupuestar y cumplir plazos fijos. La gestión predictiva se centra en la planificación, en el cálculo de presupuesto y en el marco de plazos de entrega. La gestión ágil se adapta a los cambios y se enfoca en entregar resultados tangibles y rápidos. 
Se considera éxito terminar el proyecto sin superar el coste acordado , antes de terminar la fecha acordada y con todas las funciones del plan inicial.,

**Comment by dma1009** [comment]
Corrección:
La gestión ágil surge como alternativa a la gestión predictiva, que se enfoca en planificar, presupuestar y cumplir plazos fijos. La gestión predictiva se centra en la planificación, en el cálculo de presupuesto y en el marco de plazos de entrega. Se considera éxito terminar el proyecto sin superar el coste acordado, antes de la fecha límite y con todas las funciones del plan inicial. La gestión ágil se adapta a los cambios y se enfoca en entregar resultados tangibles y rápidos y que aporten un valor al cliente.
