### ISSUE TITLE
Apartado 1.2 "El Manifiesto Ágil"

### ISSUE THREAD

**Issue by see1004** [see1004/Ing_Gest_Poyectos_101_2023#7]
El **Manifiesto ágil** reúne cuatro postulados fundamentales:
Aquello que más debemos valorar en nuestro proyecto no son los procesos ni las herramientas, sino el factor humano: los individuos y sus interacciones
Así mismo, se valora el software funcional por encima de la documentación exhaustiva. La documentación es importante a la vez que, en la mayoría de casos, obligatoria, pero el Manifiesto Ágil afirma que en muchos casos la documentación entorpece un proyecto retrasando este entre productos burocráticos. Por ello, lo ideal es presentar la menor documentación posible.
Continuando con las afirmaciones dentro del Manifiesto: Se valora más la negociación con el cliente (incluyéndolo en el desarrollo del proyecto, escuchando sus sugerencias…) que una relación meramente contractual en la que se deben establecer una serie de condiciones cerradas que en muchos casos, en caso de proyectos tecnológicos, no serán posibles debido a su continua evolución.
El cuarto de los valores definidos en El Manifiesto Ágil, decía “Valoramos más la respuesta al cambio que el seguimiento de un plan”, indicando de este modo la importancia de la capacidad de respuesta ante los continuos cambios y evolución en los proyectos.

**Comment by dma1009** [comment]
Cambios en el segundo y tercer punto:
Continuando con las afirmaciones dentro del Manifiesto: Se valora más la negociación con el cliente (incluyéndolo en el desarrollo del proyecto, escuchando sus sugerencias…) que una relación meramente contractual en la que se deben establecer una serie de condiciones cerradas que, en muchos casos, en proyectos tecnológicos, no serán posibles debido a su continua evolución.
Continuando con las afirmaciones dentro del Manifiesto: Se valora más la negociación con el 
cliente (incluyéndolo en el desarrollo del proyecto, escuchando sus sugerencias…) que una 
relación meramente contractual en la que se deben establecer una serie de condiciones 
cerradas que en muchos casos, en caso de proyectos tecnológicos, no serán posibles debido 
a su continua evolución

**Comment by dma1009** [comment]
Error en los puntos 2 y 3:
Así mismo, se valora el software funcional por encima de la documentación exhaustiva. La documentación es importante a la vez que, en la mayoría de casos, obligatoria, pero el Manifiesto Ágil afirma que en muchos casos la documentación entorpece un proyecto retrasando este por los procesos burocráticos. Por ello, lo ideal es presentar la menor documentación posible.
Continuando con las afirmaciones dentro del Manifiesto: Se valora más la negociación con el cliente (incluyéndolo en el desarrollo del proyecto, escuchando sus sugerencias…) que una relación meramente contractual en la que se deben establecer una serie de condiciones cerradas que, en muchos casos, en proyectos tecnológicos, no serán posibles debido a su continua evolución.
