### ISSUE TITLE
Apartado 2.3 "Artefactos"

### ISSUE THREAD

**Issue by dma1009** [see1004/Ing_Gest_Poyectos_101_2023#9]
Las historias de usuario de la pila del producto que pueden ser incorporados a un sprint son aquellas que están definidas, pre estimadas, son asumibles por sí mismas en un único sprint y se han establecido los criterios para considerarla terminada. Se las conoce con el término “preparada”. El objetivo de la pila del producto es describir el estado que tendrá el producto en el futuro y que muestra la visión compartida por el equipo.
Se conoce como “pila del producto” el conjunto de objetivos, funcionalidades y requisitos marcados por el cliente que deben ser llevados a cabo durante la realización del proyecto, ordenados según su prioridad. Estas indicaciones se denominan “historias de usuario”. Dado que se trata de un artefacto dinámico, esto permitirá adaptar y evolucionar los contenidos de las misma en función de las circunstancias cambiantes a las que se enfrente el desarrollo del producto. Durante la reunión de planificación del sprint, el cliente colaborará con el equipo de desarrollo para determinar las historias de usuario que conformarán el primero de los sprints. El objetivo de la pila del producto es describir el estado que tendrá el producto en el futuro y que dibuja la visión compartida por el equipo para planificar.

**Comment by dma1009** [comment]
El objetivo de la pila del producto es describir el estado que tendrá el producto en el futuro y que muestra la visión compartida por el equipo. Se conoce como “pila del producto” el conjunto de objetivos, funcionalidades y requisitos marcados por el cliente que deben ser llevados a cabo durante la realización del proyecto, ordenados según su prioridad. Estas indicaciones se denominan “historias de usuario”. Dado que se trata de un artefacto dinámico, esto permitirá adaptar y evolucionar los contenidos de las misma en función de las circunstancias cambiantes a las que se enfrente el desarrollo del producto.
Las historias de usuario de la pila del producto que pueden ser incorporados a un sprint son aquellas que están definidas, pre estimadas, son asumibles por sí mismas en un único sprint y se han establecido los criterios para considerarlas terminadas. Se las conoce con el término “preparada”.
Durante la reunión de planificación del sprint, el cliente colaborará con el equipo de desarrollo para determinar las historias de usuario que conformarán el primero de los sprints.

**Comment by dma1009** [comment]
Elementos y artefactos del modelo de gestión Scrum Master
La pila del producto
El objetivo de la pila del producto es describir el estado que tendrá el producto en el futuro y que muestra la visión compartida por el equipo. Se conoce como “pila del producto” el conjunto de objetivos, funcionalidades y requisitos marcados por el cliente que deben ser llevados a cabo durante la realización del proyecto, ordenados según su prioridad. Estas indicaciones se denominan “historias de usuario”. Dado que se trata de un artefacto dinámico, esto permitirá adaptar y evolucionar los contenidos de las misma en función de las circunstancias cambiantes a las que se enfrente el desarrollo del producto.

Historias de usuario
Las historias de usuario de la pila del producto que pueden ser incorporados a un sprint son aquellas que están definidas, pre estimadas, son asumibles por sí mismas en un único sprint y se han establecido los criterios para considerarlas terminadas. Se las conoce con el término “preparada”.

Reunión de planificación
Durante la reunión de planificación del sprint, el cliente colaborará con el equipo de desarrollo para determinar las historias de usuario que conformarán el primero de los sprints.

La pila del sprint
Lista de todas las tareas necesarias para construir las historias de usuario que se van a realizar en un sprint. Será útil para tener una comunicación visual sobre el avance del sprint. Se deben mostrar la lista de tareas, los responsables de cada tarea, el estado en el que se encuentran estas…

El incremento
Parte de producto que se encuentra en condiciones de ser entregada al cliente; es decir, terminada, probada y operativa. Hay un incremento en cada sprint a excepción del primero, que contiene los elementos básicos del proyecto.

**Comment by jbs1009** [comment]
Elementos y artefactos del modelo de gestión Scrum Master

La pila del producto
El objetivo de la pila del producto es describir el estado que tendrá el producto en el futuro y que muestra la visión compartida por el equipo. Se conoce como “pila del producto” al conjunto de funcionalidades, correcciones y mejoras, marcadas por el cliente y demás partes interesadas, que deben ser llevadas a cabo durante la realización del proyecto, ordenados según su prioridad y que serán implementadas en los sucesivos sprints. Estas indicaciones se denominan “historias de usuario”. Dado que se trata de un artefacto dinámico, esto permitirá adaptar y evolucionar los contenidos de las misma en función de las circunstancias cambiantes a las que se enfrente el desarrollo del producto.

Historias de usuario
Las historias de usuario de la pila del producto que pueden ser incorporadas a un sprint son aquellas que están definidas, preestimadas, son asumibles por sí mismas en un único sprint y de las cuales se han establecido los criterios para considerarlas terminadas. Se las conoce con el término “preparadas” o "ready". Durante la reunión de planificación del sprint, el cliente colaborará con el equipo de desarrollo para determinar las historias de usuario que serán incorporadas al finalizar el sprint en cuestión.

La pila del sprint
Lista de todas las tareas necesarias para construir las historias de usuario que se van a realizar en un sprint. Será útil para tener una comunicación visual sobre el avance del sprint. Se deben mostrar la lista de tareas, los responsables de cada tarea, el estado en el que se encuentran estas… Esta solamente podrá ser modificada o actualizada por los propios desarrolladores del producto.

El incremento
Parte de producto que se encuentra en condiciones de ser entregada al cliente, es decir, terminada, probada y operativa. Hay un incremento en cada sprint a excepción del primero, denominado generalmente como "sprint cero", que contiene los elementos básicos del proyecto.
